#!/usr/bin/env python3
"""Regenerate cmake/sources.cmake from the R0 MSVC project file.

The R0 snapshot has no Makefile/CMakeLists; muscle/src/muscle.vcxproj is the
authoritative compile-unit list (225 ClCompile entries, all files present).
This tool extracts that list verbatim and writes an explicit CMake source
list.  It never globs the source directory, so stale test/duplicate-main files
that are *not* part of the project cannot leak into the build.

Usage:
    python3 muscle/cmake/gen_sources_from_vcxproj.py [--check]

--check exits non-zero if the generated file would differ from the committed
one (used by CTest to detect a source list that no longer matches the vcxproj).

Verified facts (2026-10, R0 snapshot):
  * vcxproj ClCompile entries: 225
  * every referenced file exists in muscle/src
  * exactly one of them (main.cpp) defines main()
"""

import argparse
import hashlib
import os
import re
import sys
import xml.etree.ElementTree as ET

NS = "{http://schemas.microsoft.com/developer/msbuild/2003}"

HERE = os.path.dirname(os.path.abspath(__file__))
MUSCLE_DIR = os.path.dirname(HERE)
SRC_DIR = os.path.join(MUSCLE_DIR, "src")
VCXPROJ = os.path.join(SRC_DIR, "muscle.vcxproj")
OUT_CMAKE = os.path.join(HERE, "sources.cmake")

# Compile units that must be excluded from the shared static library because
# they own process entry points (verified: only main.cpp).
MAIN_UNITS = {"main.cpp"}


def read_units():
    tree = ET.parse(VCXPROJ)
    root = tree.getroot()
    units = []
    for item_group in root.findall(NS + "ItemGroup"):
        for cc in item_group.findall(NS + "ClCompile"):
            include = cc.get("Include")
            if include:
                units.append(include.replace("\\", "/"))
    return units


def verify(units):
    problems = []
    seen = set()
    for u in units:
        if u in seen:
            problems.append("duplicate ClCompile entry: %s" % u)
        seen.add(u)
        if not os.path.isfile(os.path.join(SRC_DIR, u)):
            problems.append("missing file referenced by vcxproj: %s" % u)
    extra_mains = []
    for u in units:
        if u in MAIN_UNITS:
            continue
        path = os.path.join(SRC_DIR, u)
        with open(path, "r", errors="replace") as f:
            text = f.read()
        if re.search(r"^\s*int\s+main\s*\(", text, re.M):
            extra_mains.append(u)
    if extra_mains:
        problems.append("unexpected main() in: %s" % ", ".join(extra_mains))
    return problems


def render(units):
    main_units = [u for u in units if u in MAIN_UNITS]
    core_units = [u for u in units if u not in MAIN_UNITS]
    with open(VCXPROJ, "rb") as f:
        vcx_sha = hashlib.sha256(f.read()).hexdigest()
    lines = []
    lines.append("# Generated by cmake/gen_sources_from_vcxproj.py -- do not edit.")
    lines.append("#")
    lines.append("# Compile-unit list extracted verbatim from src/muscle.vcxproj (R0).")
    lines.append("# vcxproj sha256: %s" % vcx_sha)
    lines.append("# units: %d (core %d, main %d)" % (len(units), len(core_units), len(main_units)))
    lines.append("")
    lines.append("set(MUSCLE_MAIN_UNITS")
    for u in main_units:
        lines.append('    "%s"' % u)
    lines.append(")")
    lines.append("")
    lines.append("set(MUSCLE_VCXPROJ_SHA256 \"%s\")" % vcx_sha)
    lines.append("")
    lines.append("set(MUSCLE_CORE_UNITS")
    for u in core_units:
        lines.append('    "%s"' % u)
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed sources.cmake is up to date and exit")
    args = ap.parse_args()

    units = read_units()
    problems = verify(units)
    if problems:
        for p in problems:
            print("ERROR: %s" % p, file=sys.stderr)
        return 2
    text = render(units)
    if args.check:
        try:
            with open(OUT_CMAKE, "r") as f:
                have = f.read()
        except IOError:
            print("ERROR: %s missing" % OUT_CMAKE, file=sys.stderr)
            return 2
        if have != text:
            print("ERROR: %s is stale; re-run this script" % OUT_CMAKE, file=sys.stderr)
            return 2
        print("sources.cmake OK: %d units" % len(units))
        return 0
    with open(OUT_CMAKE, "w") as f:
        f.write(text)
    print("wrote %s: %d units (%d core + %d main)"
          % (OUT_CMAKE, len(units), len(units) - len(MAIN_UNITS), len(MAIN_UNITS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
